language: go
go:
  - 1.2
  - tip
env:
  - GOARCH=amd64

install:
  - go get github.com/gorilla/mux

script:
  - go test

notifications:
  email:
    recipients:
      - ynpangchong@gmail.com
    on_success: change
    on_failure: always
