language: go
go:
  - 1.2
  - tip
env:
  - GOARCH=amd64

install: make get-deps

script: go test ./...

notifications:
  email:
    recipients:
      - ynpangchong@gmail.com
    on_success: change
    on_failure: always
